version: '3.8'

services:
  web:
    build: .
    ports:
      - "6005:6000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=63794
      - MYSQL_HOST=mysql
      - MYSQL_USER=root
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydb
    depends_on:
      - redis
      - mysql
  redis:
    image: redis:6.2-alpine
    ports:
      - "63794:63794"
    volumes:
      - redis_data:/data

  mysql:
    image: mysql:8.0
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=mydb
    volumes:
      - mysql_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password
    
volumes:
  redis_data:
  mysql_data:
